/**
 * TxtIndex.java, Tuesday, January 11, 2011 4:41:15 PM CST
 * 
 * Copyright (c) 2010 UC Mobile, All rights reserved.
 */

package cn.uc;


/**
 * T contains the constants as index of each localize text.
 * 
 * <p>
 * <strong>THIS CLASS IS GENERATED BY TOOLS, DONT MODIFY IT MANUALLY!</strong>
 * </p>
 * 
 * @since 7.6
 * @author <a href="mailto:yixx@ucweb.com">Roger Yi</a>
 * @see {@link Resource.getText}
 */
public final class T {

	/** "页面属性" */
	public static final int COMMAND_PAGEATTRIBUTE = 0;
	/** "输入网址" */
	public static final int COMMON_URL_INPUT = 1;
	/** "复制" */
	public static final int COMMON_COPY = 2;
	/** "菜单" */
	public static final int MENU_MENU = 3;
	/** "打开" */
	public static final int MENU_OPEN = 4;
	/** "首页" */
	public static final int MENU_HOME_PAGE = 5;
	/** "书签" */
	public static final int MENU_BOOKMARK = 6;
	/** "帮助" */
	public static final int MENU_HELP = 7;
	/** "书签" */
	public static final int BOOKMARK_BOOKMARK = 6;
	/** "菜单" */
	public static final int BOOKMARK_MENU = 3;
	/** "返回" */
	public static final int BOOKMARK_BACK = 8;
	/** "打开" */
	public static final int BOOKMARK_OPEN = 4;
	/** "新增" */
	public static final int BOOKMARK_ADD = 9;
	/** "新增书签" */
	public static final int BOOKMARK_ADD_BOOKMARD = 10;
	/** "新增目录" */
	public static final int BOOKMARK_ADD_CATALOG = 11;
	/** "管理" */
	public static final int BOOKMARK_MANAGE = 12;
	/** "编辑" */
	public static final int BOOKMARK_EDIT = 13;
	/** "上移" */
	public static final int BOOKMARK_MOVE_UP = 14;
	/** "下移" */
	public static final int BOOKMARK_MOVE_DOWN = 15;
	/** "移至目录" */
	public static final int BOOKMARK_MOVE_TO_CATALOG = 16;
	/** "同步管理" */
	public static final int BOOKMARK_SYNCHRONIZE_MANAGE = 17;
	/** "删除" */
	public static final int BOOKMARK_DELETE = 18;
	/** "删除全部" */
	public static final int BOOKMARK_DELETE_ALL = 19;
	/** "导出" */
	public static final int BOOKMARK_EXPORT = 20;
	/** "导入" */
	public static final int BOOKMARK_IMPORT = 21;
	/** "目录" */
	public static final int BOOKMARK_CATALOG = 22;
	/** "标题" */
	public static final int BOOKMARK_TITLE = 23;
	/** "路径" */
	public static final int BOOKMARK_PATH = 24;
	/** "保存" */
	public static final int BOOKMARK_SAVE = 25;
	/** "修改书签" */
	public static final int BOOKMARK_MODE_BOOKMARK = 26;
	/** "修改目录" */
	public static final int BOOKMARK_MODE_CATALOG = 27;
	/** "确定" */
	public static final int BOOKMARK_SURE = 28;
	/** "确定删除书签?" */
	public static final int BOOKMARK_SURE_DELETE = 29;
	/** "/" */
	public static final int BOOKMARK_SEMICOLON = 30;
	/** "确定删除所有书签?" */
	public static final int BOOKMARK_SURE_DELETE_ALL_BOOKMARD = 31;
	/** "输入内容不完整,请填写完整后继续!" */
	public static final int BOOKMARK_MAKEUP_INPUT = 32;
	/** "书签同步" */
	public static final int BOOKMARK_SYNCHRONIZE = 33;
	/** "后台打开" */
	public static final int BOOKMARK_OPEN_BACK = 34;
	/** "同名书签已存在,是否要覆盖原有书签?" */
	public static final int BOOKMARK_OVERWRITE = 35;
	/** "移至页顶" */
	public static final int BOOKMARK_MOVE_TOP = 36;
	/** "移至页底" */
	public static final int BOOKMARK_MOVE_BOTTOM = 37;
	/** "分享书签" */
	public static final int BOOKMARK_SHARE = 38;
	/** "设为导航" */
	public static final int BOOKMARK_SAVE_AS_NAVI = 39;
	/** "该目录已存在" */
	public static final int BOOKMARK_CATALOG_EXIST = 40;
	/** "提交" */
	public static final int COMMON_SUBMIT = 41;
	/** "重置" */
	public static final int COMMON_RESET = 42;
	/** "请输入网址" */
	public static final int COMMON_INPUT_URL = 43;
	/** "搜 索" */
	public static final int COMMON_SEARCH = 44;
	/** "放大比例" */
	public static final int COMMON_ZOOM_IN = 45;
	/** "请选择" */
	public static final int COMMON_CHOOSE = 46;
	/** "网络正常" */
	public static final int COMMON_NETWORK_OK = 47;
	/** "网络连接错误，请联系您的服务提供商查询网络设置。" */
	public static final int COMMON_NETWORK_ERROR = 48;
	/** "建议退出UC浏览器并重新初始化," */
	public static final int COMMON_SUGGEST_EXIT = 49;
	/** "书签" */
	public static final int COMMON_BOOKMARK = 6;
	/** "历史" */
	public static final int COMMON_HISTORY = 50;
	/** "更多" */
	public static final int COMMON_MORE = 51;
	/** "空键值" */
	public static final int COMMON_NULL = 52;
	/** "提示:可用存储空间少,请及时清理磁盘数据!" */
	public static final int COMMON_INSUFFICIENT_LIGHT = 53;
	/** "皮肤管理" */
	public static final int COMMON_SKIN_MANAGE = 54;
	/** "使用" */
	public static final int COMMON_USE = 55;
	/** "更多皮肤下载>>" */
	public static final int COMMON_MORE_SKIN = 56;
	/** "主题安装超过限制" */
	public static final int COMMON_THEME_OUT_OF_SIZE = 57;
	/** "“确定”将调用内置浏览器进行下载;注意nokia s40三版手机需要退出程序后点击链接下载." */
	public static final int COMMON_CALL_BROWSER = 58;
	/** "未命名" */
	public static final int COMMON_NO_NAME = 59;
	/** "请输入关键字" */
	public static final int COMMON_INPUT_KEY_WORDS = 60;
	/** "流量统计" */
	public static final int COMMON_COUNT_FLOW_RATE = 61;
	/** "此主题不兼容，请下载其他主题" */
	public static final int COMMON_INCOMPATIBLE_THEME = 62;
	/** "手机号码" */
	public static final int COMMON_PHONE_NUMBER = 63;
	/** "消息内容" */
	public static final int COMMON_MESSAGE = 64;
	/** "发送" */
	public static final int COMMON_SEND = 65;
	/** "推荐好友" */
	public static final int COMMON_RECOMMEND_FRIEND = 66;
	/** "使用中" */
	public static final int COMMON_USING = 67;
	/** "短信发送" */
	public static final int COMMON_SENDBYMESSAGE = 68;
	/** "提示" */
	public static final int COMMON_ALERT = 69;
	/** "确定退出UC浏览器?" */
	public static final int COMMON_SURE_EXIT = 70;
	/** "象素" */
	public static final int COMMON_PIX = 71;
	/** "复制失败" */
	public static final int COMMON_COPY_FAIL = 72;
	/** "剪贴板内容为空!" */
	public static final int COMMON_COPY_NULL = 73;
	/** "剪贴板" */
	public static final int COMMON_CLIBORD = 74;
	/** "确定" */
	public static final int COMMON_SURE = 28;
	/** "修改" */
	public static final int COMMON_MODE = 75;
	/** "删除" */
	public static final int COMMON_DELETE = 18;
	/** "删除全部" */
	public static final int COMMON_DELETE_ALL = 19;
	/** "返回" */
	public static final int COMMON_BAKC = 8;
	/** "注册" */
	public static final int COMMON_REGIST = 76;
	/** "页面属性" */
	public static final int COMMON_PAGE_PROPERTY = 0;
	/** "页面URL" */
	public static final int COMMON_PAGE_URL = 77;
	/** "链接URL" */
	public static final int COMMON_LINK_URL = 78;
	/** "图片URL" */
	public static final int COMMON_PHOTO_URL = 79;
	/** "可用内存" */
	public static final int COMMON_AVAILABLE_MEMORY = 80;
	/** "总共内存" */
	public static final int COMMON_TOTOL_MEMORY = 81;
	/** "操作成功!" */
	public static final int COMMON_OPERATE_OK = 82;
	/** "确认进行此操作?" */
	public static final int COMMON_CONFIRM_OPERATE = 83;
	/** "操作失败!" */
	public static final int COMMON_OPERATE_FAIL = 84;
	/** "浏览..." */
	public static final int COMMON_BROWSE = 85;
	/** "无输入记录!" */
	public static final int COMMON_NO_INPUT = 86;
	/** "页面URL:" */
	public static final int COMMON_PAGE_URL_WITH_COLON = 87;
	/** "焦点图片URL:" */
	public static final int COMMON_FOCUS_PHOTO_URL = 88;
	/** "焦点链接URL:" */
	public static final int COMMON_FOCUS_LINK_URL = 89;
	/** "页面标题:" */
	public static final int COMMON_PAGE_TITLE = 90;
	/** "图片数量:" */
	public static final int COMMON_PHOTO_NUMBER = 91;
	/** "对象数量:" */
	public static final int COMMON_OBJECT_NUMBER = 92;
	/** "总内存:" */
	public static final int COMMON_TOTOL_MEMORY_WITH_COLON = 93;
	/** "可用内存:" */
	public static final int COMMON_AVAILABLE_MEMORY_WITH_COLON = 94;
	/** "上传" */
	public static final int COMMON_UPLOAD = 95;
	/** "下载" */
	public static final int COMMON_DOWNLOAD = 96;
	/** "页面缓存" */
	public static final int COMMON_PAGE_CACHE = 97;
	/** "输入历史" */
	public static final int COMMON_INPUT_HISTORY = 98;
	/** "访问历史" */
	public static final int COMMON_ACCESS_HISTORY = 99;
	/** "访问流量" */
	public static final int COMMON_ACCESS_FLOW_RATE = 100;
	/** "COOKIES" */
	public static final int COMMON_COOKIES = 101;
	/** "清除成功!" */
	public static final int COMMON_CLEAN_OK = 102;
	/** "编辑" */
	public static final int COMMON_EDITE = 13;
	/** "错误" */
	public static final int COMMON_ERROR = 103;
	/** "搜索引擎" */
	public static final int COMMON_SEARCH_ENGINE = 104;
	/** "窗口个数限制为" */
	public static final int COMMON_WINDOW_NUMBER_LIMIT = 105;
	/**
	 * "“确定”将调用内置浏览器进行下载，即时安装；按确定继续，nokia s40手机需要退出程序后下载.“取消”将使用断点续传进行下载，不能即时安装"
	 */
	public static final int COMMON_SURE_SETUP_SOON = 106;
	/** "嗨，我在玩UC浏览器，上网读新闻、看小说、下载音乐视频，又快又省流量，推荐你也用一下http://wap.uc.cn" */
	public static final int COMMON_RECOMMEND_FRIEND_MESSAGE = 107;
	/** "显示原图" */
	public static final int COMMON_SHOW_ORIGINAL_PHOTO = 108;
	/** "适应屏幕" */
	public static final int COMMON_FIT_SCREEN = 109;
	/** "文件名" */
	public static final int COMMON_FILE_NAME = 110;
	/** "安装" */
	public static final int COMMON_SETUP = 111;
	/** "打开" */
	public static final int COMMON_OPEN = 4;
	/** "保存" */
	public static final int COMMON_SAVE = 25;
	/** "取消" */
	public static final int COMMON_CANCEL = 112;
	/** ": 调用自带浏览器下载安装" */
	public static final int COMMON_CALL_BROWSER_SETUP = 113;
	/** ": 调用自带浏览器下载并打开文件" */
	public static final int COMMON_CALL_BROWSER_OPEN = 114;
	/** ": 用UC浏览器下载文件并保存到手机上" */
	public static final int COMMON_CALL_BROWSER_SAVE = 115;
	/** "小提示" */
	public static final int COMMON_HINT_INKING = 116;
	/** "安装失败" */
	public static final int COMMON_SETUP_FAIL = 117;
	/** "皮肤下载" */
	public static final int COMMON_DOWNLOAD_THEME = 118;
	/** "预览: 可直接查看文件内容" */
	public static final int COMMON_PREVIEW = 119;
	/** ": 不推荐选择,仅供高级用户使用" */
	public static final int COMMON_NOT_SUGGEST_FOR_RUNNER = 120;
	/** "(推荐)" */
	public static final int COMMON_SUGGEST = 121;
	/** "(不推荐)" */
	public static final int COMMON_NOT_SUGGEST = 122;
	/** "确定恢复UC浏览器默认设置并删除所有用户数据？" */
	public static final int COMMON_SURE_RESET = 123;
	/** "默认1键浏览大图" */
	public static final int COMMON_BROWSER_BIG_PHOTO = 124;
	/** "复制成功" */
	public static final int COMMON_COPY_OK = 125;
	/** "复制失败,复制内容过多" */
	public static final int COMMON_COPY_FAILED_FOR_TOO_MORE = 126;
	/** "粘贴失败,粘贴内容过多" */
	public static final int COMMON_PASTE_FAILED_FOR_TOO_MORE = 127;
	/** "请输入内容" */
	public static final int COMMON_INPUT_PLEASE = 128;
	/** "不支持播放" */
	public static final int COMMON_UNABLE_PLAY = 129;
	/** "该功能使用普通短信方式进行发送，不会产生额外的费用。" */
	public static final int COMMON_SEND_MESSAGE_FREE = 130;
	/** "拍照上传" */
	public static final int COMMON_TAKE_PHOTOS_UPLOAD = 131;
	/** "初始化摄像头中..." */
	public static final int COMMON_INIT_CAMERA = 132;
	/** "照片大小:" */
	public static final int COMMON_PHOTO_SIZE = 133;
	/** "拍照上传照片" */
	public static final int COMMON_TAKE_PHOTOS_AND_UPLOAD = 134;
	/** "初始化失败!" */
	public static final int COMMON_INIT_FAILED = 135;
	/** "处理图片中..." */
	public static final int COMMON_HANDLING_PHOTO = 136;
	/** "启动拍照失败,建议您重启浏览器后重试" */
	public static final int COMMON_RUN_CAMERA_FAILED = 137;
	/** "【温馨提示】" */
	public static final int COMMON_WARM_SUGGESTION = 138;
	/** "1.索爱手机首次使用相机功能需要重启浏览器" */
	public static final int COMMON_WARM_SUGGESTION_FOR_SONYERSSION = 139;
	/** "2.系统询问是否允许调用摄像头时,请选择是" */
	public static final int COMMON_WARM_SUGGESTION_FOR_CHECK = 140;
	/** "数据更新中，请稍候" */
	public static final int COMMON_DATA_UPDATING = 141;
	/** "扫描操作失败！" */
	public static final int COMMON_SCAN_FAILED = 142;
	/** "确定删除全部剪贴条目？" */
	public static final int COMMON_SURE_DELETE_ALL = 143;
	/** "文件上传" */
	public static final int COMMON_FILE_UPLOAD = 144;
	/** "拍照上传" */
	public static final int COMMON_TAKE_PHOTO_UPLOAD = 131;
	/** "是" */
	public static final int COMMON_YES = 145;
	/** "否" */
	public static final int COMMON_NO = 146;
	/** "继续" */
	public static final int COMMON_CONTINUE = 147;
	/** "暂停" */
	public static final int COMMON_PAUSE = 148;
	/** "地址:" */
	public static final int COMMON_ADDRESS = 149;
	/** "内容:" */
	public static final int COMMON_CONTENT = 150;
	/** "请划动屏幕选择文本" */
	public static final int COMMON_CHOOSE_TEXT_BY_DRAG = 151;
	/** "请移动光标选择起点" */
	public static final int COMMON_CHOOSE_START = 152;
	/** "1键快捷菜单可管理我的导航" */
	public static final int COMMON_MANAGER_MYNAVI_BY_ONE_KEY = 153;
	/** "长按快捷菜单可管理我的导航" */
	public static final int COMMON_MANAGER_MYNAVI_BY_LONG_PRESS = 154;
	/** "文件大小超过允许上传最大值" */
	public static final int COMMON_FILE_OUT_OF_SIZE = 155;
	/** "当前站点限制该类型文件上传，请重新选择" */
	public static final int COMMON_FILE_TYPE_LIMIT = 156;
	/** "中国人龙的传人UCWEB-STAFF[:)]google" */
	public static final int COMMON_TEST_TEXT = 157;
	/** "切换为无图模式" */
	public static final int COMMON_TURN_TO_NO_PHOTO = 158;
	/** "切换为微缩模式" */
	public static final int COMMON_TURN_TO_MICRO_PHOTO = 159;
	/** "切换为低彩模式" */
	public static final int COMMON_TURN_TO_LESS_COLOR_PHOTO = 160;
	/** "切换为标准模式" */
	public static final int COMMON_TURN_TO_STANDARD_PHOTO = 161;
	/** "切换为全彩模式" */
	public static final int COMMON_TURN_TO_TRUE_COLOR_PHOTO = 162;
	/** "空白页" */
	public static final int COMMON_BLANK_PAGE = 163;
	/** "您是否希望UC浏览器保存您的用户密码？" */
	public static final int COMMON_FORM_PASSWORD_CONFIRM_SAVE = 164;
	/** "是否替换已保存的表单用户密码？" */
	public static final int COMMON_FORM_PASSWORD_CONFIRM_COVER = 165;
	/** "您正在分享" */
	public static final int COMMON_YOUR_SHARE = 166;
	/** "我要发布到" */
	public static final int COMMON_SEND_TO = 167;
	/** "页面加载错误" */
	public static final int WML_ERROR_ERROR_WHEN_OPEN = 168;
	/** "错误代码：" */
	public static final int WML_ERROR_ERROR_CODE = 169;
	/** "响应代码: " */
	public static final int WML_ERROR_RESPONESE_CODE = 170;
	/** " *请检查网络配置是否正确" */
	public static final int WML_ERROR_PLEASE_CHECK_NETWORK = 171;
	/** " *此站点暂不可用或者太忙" */
	public static final int WML_ERROR_TRY_AGAIN_LATER = 172;
	/** "请尝试下面操作：" */
	public static final int WML_ERROR_FOLLOWING_OPERATIONS = 173;
	/** "后退" */
	public static final int WML_ERROR_BACK = 174;
	/** "重试" */
	public static final int WML_ERROR_RETRY = 175;
	/** "检查网络" */
	public static final int WML_ERROR_CHECK_NETWORK = 176;
	/** "搜索试试" */
	public static final int WML_ERROR_TRY_TO_SEARCH = 177;
	/** "初始化" */
	public static final int INIT_STARTING = 178;
	/** " UC浏览器 " */
	public static final int INIT_UC_BROWSER = 179;
	/** " 配置数据" */
	public static final int INIT_CONFIGURATION = 180;
	/** " 动态数据" */
	public static final int INIT_DYNAMIC_DATA = 181;
	/** " 检查更新" */
	public static final int INIT_CHECKING_FOR_UPDATE = 182;
	/** " 更新数据中" */
	public static final int INIT_UPDATING_DATA = 183;
	/** " 进入UC浏览器" */
	public static final int INIT_LOADING_COMPLETED = 184;
	/** " 取消操作中" */
	public static final int INIT_OPERATION_CANCELLED = 185;
	/** " 测试网络" */
	public static final int INIT_TESTING_NETWORK = 186;
	/** " 欢迎使用UC浏览器 " */
	public static final int INIT_WELCOME_TO_UC_BROWSER = 187;
	/** " 启动中 " */
	public static final int INIT_INITIALIZING = 188;
	/** " 测试网络完毕" */
	public static final int INIT_TESTING_COMPLETED = 189;
	/** "为美化网页显示效果,正在检测手机字体,请稍候" */
	public static final int INIT_CHECKING_DEVICE_FONTS = 190;
	/** "第" */
	public static final int INIT_THE = 191;
	/** "次" */
	public static final int INIT_TIMES = 192;
	/** "联网失败" */
	public static final int INIT_CONNECTION_FAILED = 193;
	/** "建议联系本地运营商开通数据业务套餐" */
	public static final int INIT_CONTACT_LOCAL_OPERATORS = 194;
	/** "移动卡: " */
	public static final int INIT_CMCC = 195;
	/** "联通卡: " */
	public static final int INIT_UNICOM = 196;
	/** "电信卡：" */
	public static final int INIT_CT = 197;
	/** "tel:10086" */
	public static final int INIT_TEL_10086 = 198;
	/** "tel:10010" */
	public static final int INIT_TEL_10010 = 199;
	/** "tel:10000" */
	public static final int INIT_TEL_10000 = 200;
	/** "点此拨号" */
	public static final int INIT_CLICK_TO_DIAL = 201;
	/** "点此进入主页" */
	public static final int INIT_ENTER_START_PAGE = 202;
	/** "确定" */
	public static final int SMART_INPUT_OK = 28;
	/** "新窗口打开" */
	public static final int SMART_INPUT_OPEN_IN_NEW = 203;
	/** "符号/粘贴(*)" */
	public static final int SMART_INPUT_SYMBOL_PASTE = 204;
	/** "清空" */
	public static final int SMART_INPUT_CLEAR = 205;
	/** "返回" */
	public static final int SMART_INPUT_BACK = 8;
	/** "删除" */
	public static final int SMART_INPUT_DELETE = 18;
	/** "下页" */
	public static final int KYEWORDLEVEL_0 = 206;
	/** "[下页]" */
	public static final int KYEWORDLEVEL_1 = 207;
	/** "下一页" */
	public static final int KYEWORDLEVEL_2 = 208;
	/** "[下一页]" */
	public static final int KYEWORDLEVEL_3 = 209;
	/** "下页|" */
	public static final int KYEWORDLEVEL_4 = 210;
	/** ">>下页" */
	public static final int KYEWORDLEVEL_5 = 211;
	/** ">>下页|" */
	public static final int KYEWORDLEVEL_6 = 212;
	/** "下一张" */
	public static final int KYEWORDLEVEL_7 = 213;
	/** "[下一张]" */
	public static final int KYEWORDLEVEL_8 = 214;
	/** "[->>]" */
	public static final int KYEWORDLEVEL_9 = 215;
	/** ">>" */
	public static final int KYEWORDLEVEL_10 = 216;
	/** "[>>]" */
	public static final int KYEWORDLEVEL_11 = 217;
	/** ">" */
	public static final int KYEWORDLEVEL_12 = 218;
	/** "[>]" */
	public static final int KYEWORDLEVEL_13 = 219;
	/** "下章" */
	public static final int KYEWORDLEVEL_14 = 220;
	/** "[下章]" */
	public static final int KYEWORDLEVEL_15 = 221;
	/** "下一章" */
	public static final int KYEWORDLEVEL_16 = 222;
	/** "[下一章]" */
	public static final int KYEWORDLEVEL_17 = 223;
	/** "下节" */
	public static final int KYEWORDLEVEL_18 = 224;
	/** "[下节]" */
	public static final int KYEWORDLEVEL_19 = 225;
	/** "下后>" */
	public static final int KYEWORD_0 = 226;
	/** "一页章条节>" */
	public static final int KYEWORD_1 = 227;
	/** "连接网络 " */
	public static final int NETWORK_CONNECTING_NETWORK = 228;
	/** "接收数据 " */
	public static final int NETWORK_RECEIVING_DATA = 229;
	/** "下载图片 " */
	public static final int NETWORK_RECEIVING_IMAGE = 230;
	/** "打开页面 " */
	public static final int NETWORK_OPENING_PAGE = 231;
	/** "等待刷新" */
	public static final int NETWORK_RELOADING = 232;
	/** "正在打开..." */
	public static final int NETWORK_LOADING = 233;
	/** "该网站" */
	public static final int WARNING_WEB = 234;
	/** "可能存在乱扣费现象！" */
	public static final int WARNING_CHARGE_WEB = 235;
	/** "可能是假冒网站！" */
	public static final int WARNING_FAKE_WEB = 236;
	/** "可能存在潜在风险！" */
	public static final int WARNING_RISK_WEB = 237;
	/** "RMS 使用空间不足" */
	public static final int ERROR_RMS_INSUFFICIENT = 238;
	/** "字体大小" */
	public static final int SYS_CONFIG_FONT_SIZE = 239;
	/** "小" */
	public static final int SYS_CONFIG_FONT_SIZE_SMALL = 240;
	/** "中" */
	public static final int SYS_CONFIG_FONT_SIZE_MEDIUM = 241;
	/** "大" */
	public static final int SYS_CONFIG_FONT_SIZE_LARGE = 242;
	/** "图片质量" */
	public static final int SYS_CONFIG_IMAGE_QUALITY = 243;
	/** "无图" */
	public static final int SYS_CONFIG_IMAGE_QUALITY_NO = 244;
	/** "微缩" */
	public static final int SYS_CONFIG_IMAGE_QUALITY_MICRO = 245;
	/** "低彩" */
	public static final int SYS_CONFIG_IMAGE_QUALITY_LOW = 246;
	/** "标准" */
	public static final int SYS_CONFIG_IMAGE_QUALITY_NORMAL = 247;
	/** "全彩" */
	public static final int SYS_CONFIG_IMAGE_QUALITY_HIGH = 248;
	/** "网络类型" */
	public static final int SYS_CONFIG_NETWORK = 249;
	/** "移动梦网" */
	public static final int SYS_CONFIG_NETWORK_MONTERNET = 250;
	/** "直联互联网" */
	public static final int SYS_CONFIG_NETWORK_DIRECT_NETWORK = 251;
	/** "缓存页数" */
	public static final int SYS_CONFIG_CACHED_PAGE = 252;
	/** "分页大小" */
	public static final int SYS_CONFIG_PAGE_SIZE = 253;
	/** "下载分段" */
	public static final int SYS_CONFIG_BLOCK_SIZE = 254;
	/** "自带浏览器" */
	public static final int SYS_CONFIG_BUILT_IN_BROWSER = 255;
	/** "断点续传" */
	public static final int SYS_CONFIG_RESUME_FORM_BREAK_POINT = 256;
	/** "WAP预读" */
	public static final int SYS_CONFIG_WAP_PRE_LOAD = 257;
	/** "WWW预读" */
	public static final int SYS_CONFIG_WWW_PRE_LOAD = 258;
	/** "开" */
	public static final int SYS_CONFIG_ON = 259;
	/** "平滑滚动" */
	public static final int SYS_CONFIG_SMOOTH_SCROLLING = 260;
	/** "全屏浏览" */
	public static final int SYS_CONFIG_FULL_SCREEN = 261;
	/** "系统设置" */
	public static final int SYS_CONFIG_GENERAL_SETTINGS = 262;
	/** "保存成功" */
	public static final int SYS_CONFIG_SAVE_SUCCESS = 263;
	/** "二次连接" */
	public static final int SYS_CONFIG_TWICE_REQUEST = 264;
	/** "保存登陆信息" */
	public static final int SYS_CONFIG_SAVE_LOGIN_RECORDS = 265;
	/** "自动登录" */
	public static final int SYS_CONFIG_AUTO_LOGIN = 266;
	/** "浏览器类型" */
	public static final int SYS_CONFIG_BROWSER_TYPE = 267;
	/** "浏览器标识(UA)" */
	public static final int SYS_CONFIG_USER_AGENT = 268;
	/** "WAP压缩中转" */
	public static final int SYS_CONFIG_WAP_VIA_SERVER = 269;
	/** "浏览器" */
	public static final int SYS_CONFIG_BROWSER = 270;
	/** "页面优化" */
	public static final int SYS_CONFIG_PAGE_OPTIMIZATION = 271;
	/** "折叠模式" */
	public static final int SYS_CONFIG_CONTENTS_FOLDING = 272;
	/** "不使用分段" */
	public static final int SYS_CONFIG_DISABLE_SEGMENTATION = 273;
	/** "不使用" */
	public static final int SYS_CONFIG_UA_NOT_USE = 274;
	/** "UA类型" */
	public static final int SYS_CONFIG_UA_TYPE = 275;
	/** "影子连接(索爱非触摸屏系列建议打开此项)" */
	public static final int SYS_CONFIG_SHADOW_CONNECTION = 276;
	/** "背景灯设置" */
	public static final int SYS_CONFIG_BACKLIGHT_SETTINGS = 277;
	/** "横屏设置" */
	public static final int SYS_CONFIG_ROTATE_SETTINGS = 278;
	/** "左横屏" */
	public static final int SYS_CONFIG_ROTATE_TO_LEFT = 279;
	/** "右横屏" */
	public static final int SYS_CONFIG_ROTATE_TO_RIGHT = 280;
	/** "滚动条设置" */
	public static final int SYS_CONFIG_SCROLLING_BAR_SETTINGS = 281;
	/** "不设置" */
	public static final int SYS_CONFIG_NOT_SETTING = 282;
	/** "设置代理服务器" */
	public static final int SYS_CONFIG_PROXY = 283;
	/** "默认代理" */
	public static final int SYS_CONFIG_DEFAULT = 284;
	/** "消息提示" */
	public static final int SYS_CONFIG_POP_UPS = 285;
	/** "不接收" */
	public static final int SYS_CONFIG_POP_UPS_NO = 286;
	/** "接收" */
	public static final int SYS_CONFIG_POP_UPS_YES = 287;
	/** "网址输入智能匹配" */
	public static final int SYS_CONFIG_URL_INPUT_MATCH = 288;
	/** "缩放模式" */
	public static final int SYS_CONFIG_ZOOM_MODE = 289;
	/** "声音提示" */
	public static final int SYS_CONFIG_VOICE_PROMPT = 290;
	/** "安全设置" */
	public static final int SYS_CONFIG_SAFE_SETTING = 291;
	/** "表单用户密码" */
	public static final int SYS_CONFIG_FORM_PASSWORD = 292;
	/** "提示保存" */
	public static final int SYS_CONFIG_FORM_PASSWORD_CONFIRM_SAVE = 293;
	/** "自动保存" */
	public static final int SYS_CONFIG_FORM_PASSWORD_AUTO_SAVE = 294;
	/** "不保存" */
	public static final int SYS_CONFIG_FORM_PASSWORD_UN_SAVE = 295;
	/** "网址安全提示" */
	public static final int SYS_CONFIG_SAFE_SETTING_URL_PROMPT = 296;
	/** "下载前安全提示" */
	public static final int SYS_CONFIG_SAFE_SETTING_PRE_DOWNLOAD_PROMPT = 297;
	/** "已设置关闭下载前安全扫描!" */
	public static final int SYS_CONFIG_SAFE_SETTING_SHUTDOWN_PRE_DOWNLOAD_SCAN = 298;
	/** "记录最常访问" */
	public static final int SYS_CONFIG_SAFE_SETTING_MOST_VISITED = 299;
	/** "我的导航" */
	public static final int SYS_CONFIG_MY_NAV = 300;
	/** "一行" */
	public static final int SYS_CONFIG_MY_NAV_ONE_ROW = 301;
	/** "两行" */
	public static final int SYS_CONFIG_MY_NAV_TWO_ROW = 302;
	/** "已开启WWW预读!" */
	public static final int SYS_CONFIG_WWW_PRE_LOAD_ON = 303;
	/** "已关闭WWW预读!" */
	public static final int SYS_CONFIG_WWW_PRE_LOAD_OFF = 304;
	/** "代理地址:端口" */
	public static final int SYS_CONFIG_PROXY_PORT = 305;
	/** "例如: 10.0.0.186:8080" */
	public static final int SYS_CONFIG_PROXY_EXAMPLE = 306;
	/** "设置连接网络的代理服务器，代理地址错误将导致浏览器不能联网，不建议初始用户设置" */
	public static final int SYS_CONFIG_PROXY_PROMPT = 307;
	/** "以下域名使用代理访问" */
	public static final int SYS_CONFIG_PROXY_HOST_SETTING = 308;
	/** "不同域名间以','分隔" */
	public static final int SYS_CONFIG_PROXY_HOST_SETTING_PROMPT = 309;
	/** "例如: uc.cn, bbs.uc.cn" */
	public static final int SYS_CONFIG_PROXY_HOST_SETTING_EXAMPLE = 310;
	/** "设置使用代理访问的域名，如本项为空，则默认代理服务器设置项无效" */
	public static final int SYS_CONFIG_PROXY_HOST_SETTING_WARNING = 311;
	/** "标题：" */
	public static final int MY_NAVIGATION_TITLE = 312;
	/** "网址：" */
	public static final int MY_NAVIGATION_URL = 313;
	/** "从书签选择" */
	public static final int MY_NAVIGATION_SELECT_FROM_BOOKMARK = 314;
	/** "从历史选择" */
	public static final int MY_NAVIGATION_SELECT_FROM_HISTORY = 315;
	/** "您已重复添加，操作失败" */
	public static final int MY_NAVIGATION_ERROR_ALREADY_EXIST = 316;
	/** "标题或网址不能为空" */
	public static final int MY_NAVIGATION_ERROR_NOT_NULL = 317;
	/** "操作失败" */
	public static final int MY_NAVIGATION_OPERATION_FAILED = 318;
	/** "点击加载游戏" */
	public static final int GAME_CLICK_TO_LOAD = 319;
	/** "数据加载中...点击取消加载" */
	public static final int GAME_CLICK_TO_CANCLE_ON_LOADING = 320;
	/** "加载完成,点击运行游戏" */
	public static final int GAME_CLICK_TO_RUN_ON_COMPLETE = 321;
	/** "长按“*”键退出游戏" */
	public static final int GAME_LONG_PRESS_STAR_TO_EXIT = 322;
	/** "游戏加载失败，请点击重新加载" */
	public static final int GAME_CLICK_TO_RELOAD_ON_LOADING_ERROR = 323;
	/** "资源加载失败" */
	public static final int GAME_RESOURCE_LOADING_ERROR = 324;
	/** "存在另外一个游戏正在加载，请先取消" */
	public static final int GAME_CANCLE_OTHER_LOADING_GAME = 325;
	/** "加载取消，点击重新加载!" */
	public static final int GAME_CLICK_TO_RELOAD_ON_PAUSE = 326;
	/** "取消中..." */
	public static final int GAME_ON_CANCLE = 327;
	/** "导航" */
	public static final int MENU_NAVIGATION = 328;
	/** "工具" */
	public static final int MENU_TOOLS = 329;
	/** "手机" */
	public static final int MENU_CELLPHONE = 330;
	/** "设置" */
	public static final int MENU_SETTINGS = 331;
	/** "退出" */
	public static final int MENU_EXIT = 332;
	/** "网址" */
	public static final int MENU_WEBSITE = 333;
	/** "快捷搜索" */
	public static final int MENU_QUICK_SEARCH = 334;
	/** "搜索" */
	public static final int MENU_SEARCH = 335;
	/** "地盘" */
	public static final int MENU_ZONE = 336;
	/** "刷新" */
	public static final int MENU_REFRESH = 337;
	/** "损坏" */
	public static final int MENU_BROKEN = 338;
	/** "前进" */
	public static final int MENU_FORWARD = 339;
	/** "后退" */
	public static final int MENU_BACKWARD = 174;
	/** "目标另存" */
	public static final int MENU_SAVE_AS = 340;
	/** "系统设置" */
	public static final int MENU_SYSTEM_SETTINGS = 262;
	/** "显示设置" */
	public static final int MENU_DISPLAY_SETTINGS = 341;
	/** "网络设置" */
	public static final int MENU_NETWORK_SETTINGS = 342;
	/** "浏览器设置" */
	public static final int MENU_BROSWER_SETTINGS = 343;
	/** "窗口" */
	public static final int MENU_WINDOW = 344;
	/** "向右切换" */
	public static final int MENU_SWITCH_RIGHT = 345;
	/** "向左切换" */
	public static final int MENU_SWITCH_LEFT = 346;
	/** "新建窗口" */
	public static final int MENU_CREATE_NEW_WINDOW = 347;
	/** "关闭当前" */
	public static final int MENU_CLOSE_CURRENT = 348;
	/** "后台打开" */
	public static final int MENU_OPEN_IN_BACKGROUND = 34;
	/** "存储空间不足" */
	public static final int MENU_OUT_OF_STORAGE = 349;
	/** "请不要移动或删除带“*”皮肤的uct文件" */
	public static final int MENU_DONT_DEL_SYS_UCT = 350;
	/** "加入书签" */
	public static final int MENU_ADD_BOOKMARK = 351;
	/** "发送短信" */
	public static final int MENU_SEND_SHORT_MESSAGE = 352;
	/** "个人设置" */
	public static final int MENU_PERSONAL_SETTINGS = 353;
	/** "复制" */
	public static final int MENU_COPY = 2;
	/** "选中文字" */
	public static final int MENU_SELECTED_TEXT = 354;
	/** "选中链接" */
	public static final int MENU_SELECTED_LINK = 355;
	/** "当前屏幕" */
	public static final int MENU_CURRENT_SCREEN = 356;
	/** "文件管理" */
	public static final int MENU_FILE_MANAGE = 357;
	/** "文件" */
	public static final int MENU_FILE = 358;
	/** "下载管理" */
	public static final int MENU_DOWNLOAD_MANAGE = 359;
	/** "快捷键" */
	public static final int MENU_SHORTCUT_KEYS = 360;
	/** "恢复默认" */
	public static final int MENU_RESTORE_DEFAULT = 361;
	/** "清除记录" */
	public static final int MENU_CLEAR_RECORD = 362;
	/** "页内查找" */
	public static final int MENU_FIND_IN_PAGE = 363;
	/** "图片浏览" */
	public static final int MENU_SHOW_PHOTOS = 364;
	/** "整个页面" */
	public static final int MENU_WHOLE_PAGE = 365;
	/** "存至网盘" */
	public static final int MENU_SAVE_TO_NETDISK = 366;
	/** "拨打电话" */
	public static final int MENU_DIALUP = 367;
	/** "更换皮肤" */
	public static final int MENU_SWITCH_SKIN = 368;
	/** "未知" */
	public static final int MENU_UNKNOWN = 369;
	/** "横屏切换" */
	public static final int MENU_SWITCH_ORIENTATION = 370;
	/** "检查网络" */
	public static final int MENU_CHECK_NETWORK = 176;
	/** "后台运行" */
	public static final int MENU_RUN_IN_BACKGROUND = 371;
	/** "关闭其它" */
	public static final int MENU_CLOSE_OTHERS = 372;
	/** "保存图片" */
	public static final int MENU_SAVE_PHOTO = 373;
	/** "关闭窗口" */
	public static final int MENU_CLOSE_WINDOW = 374;
	/** "历史" */
	public static final int MENU_HISTORY = 50;
	/** "快捷菜单" */
	public static final int MENU_SHORTCUT_MENU = 375;
	/** "字体大小" */
	public static final int MENU_FONT_SIZE = 239;
	/** "大字体" */
	public static final int MENU_LARGE_FONT = 376;
	/** "中字体" */
	public static final int MENU_MIDDLE_FONT = 377;
	/** "小字体" */
	public static final int MENU_SMALL_FONT = 378;
	/** "关于" */
	public static final int MENU_ABOUT = 379;
	/** "分享" */
	public static final int MENU_SHARE = 380;
	/** "操作模式" */
	public static final int MENU_OPERATION_MODE = 381;
	/** "常用模式" */
	public static final int MENU_COMMON_MODE = 382;
	/** "鼠标模式" */
	public static final int MENU_MOUSE_MODE = 383;
	/** "帮助说明" */
	public static final int MENU_HELP_DISCRIPTION = 384;
	/** "社区分享" */
	public static final int MENU_SHARED_BY_WEIBLOG = 385;
	/** "短信分享" */
	public static final int MENU_SHARED_BY_SHORT_MESSAGE = 386;
	/** "举报网站" */
	public static final int MENU_REPORT_WEBSITE = 387;
	/** "解除固定" */
	public static final int MENU_RELEASE_FIX = 388;
	/** "固定" */
	public static final int MENU_FIX = 389;
	/** "添加" */
	public static final int MENU_ADD = 390;
	/** "编辑" */
	public static final int MENU_EDIT = 13;
	/** "删除" */
	public static final int MENU_DELETE = 18;
	/** "自由复制" */
	public static final int MENU_FREESTYLE_COPY = 391;
	/** "反馈意见" */
	public static final int MENU_FEEDBACK = 392;
	/** "菜单" */
	public static final int CMD_MENU = 3;
	/** "取消" */
	public static final int CMD_CANCEL = 112;
	/** "保存" */
	public static final int CMD_SAVE = 25;
	/** "前进" */
	public static final int CMD_FORWARD = 339;
	/** "后退" */
	public static final int CMD_BACKWARD = 174;
	/** "确定" */
	public static final int CMD_CONFIRM = 28;
	/** "返回" */
	public static final int CMD_RETURN = 8;
	/** "切换" */
	public static final int CMD_SWITCH = 393;
	/** "选择" */
	public static final int CMD_SELECT = 394;
	/** "搜索" */
	public static final int CMD_SEARCH = 335;
	/** "微缩" */
	public static final int CMD_ZOOM_OUT = 245;
	/** "拍照" */
	public static final int CMD_CAPTURE = 395;
	/** "重拍" */
	public static final int CMD_RECAPTURE = 396;
	/** "开始" */
	public static final int CMD_START = 397;
	/** "使用" */
	public static final int CMD_USE = 55;
	/** "关闭" */
	public static final int CMD_CLOSE = 398;
	/** "下一条" */
	public static final int CMD_NEXT = 399;
	/** "清空" */
	public static final int CMD_CLEAR = 205;
	/** "粘贴" */
	public static final int CMD_PASTE = 400;
	/** "输入历史" */
	public static final int CMD_INPUT_HISTORY = 98;
	/** "返回主页" */
	public static final int SHORTCUT_RETURN_HOME = 401;
	/** "快捷菜单" */
	public static final int SHORTCUT_MENU = 375;
	/** "向上移动" */
	public static final int SHORTCUT_MOVE_UP = 402;
	/** "多窗口切换" */
	public static final int SHORTCUT_MULTI_WIN_SWITCH = 403;
	/** "上翻页/左移动" */
	public static final int SHORTCUT_SCROLL_UP = 404;
	/** "确认/查看消息" */
	public static final int SHORTCUT_CONFIRM = 405;
	/** "下翻页/右移动" */
	public static final int SHORTCUT_SCROLL_DOWN = 406;
	/** "后退" */
	public static final int SHORTCUT_BACKWARD = 174;
	/** "向下移动" */
	public static final int SHORTCUT_MOVE_DOWN = 407;
	/** "前进" */
	public static final int SHORTCUT_FORWARD = 339;
	/** "刷新" */
	public static final int SHORTCUT_REFRESH = 337;
	/** "输入网址" */
	public static final int SHORTCUT_INPUT = 1;
	/** "窗口-新建后台" */
	public static final int SHORTCUT_NEW_BG_WIN = 408;
	/** "窗口-上一个" */
	public static final int SHORTCUT_PRE_WIN = 409;
	/** "快捷搜索" */
	public static final int SHORTCUT_QUICK_SEARCH = 334;
	/** "窗口-关闭当前" */
	public static final int SHORTCUT_CLOSE_WIN = 410;
	/** "自由复制" */
	public static final int SHORTCUT_FREESTYLE_COPY = 391;
	/** "页首/页尾" */
	public static final int SHORTCUT_PAGE_BEGIN_END = 411;
	/** "无图切换" */
	public static final int SHORTCUT_NO_PHOTO_SWITCH = 412;
	/** "切换全屏" */
	public static final int SHORTCUT_FULLSCREEN_SWITCH = 413;
	/** "系统设置" */
	public static final int SHORTCUT_SYSTEM_SETTINGS = 262;
	/** "页面属性" */
	public static final int SHORTCUT_PAGE_ATTRIBUTES = 0;
	/** "清除记录" */
	public static final int SHORTCUT_CLEAR_RECORD = 362;
	/** "下载管理" */
	public static final int SHORTCUT_DOWNLOAD_MANAGE = 359;
	/** "主题切换" */
	public static final int SHORTCUT_THEME_SWITCH = 414;
	/** "横屏切换" */
	public static final int SHORTCUT_SWITCH_ORIENTATION = 370;
	/** "保存图片" */
	public static final int SHORTCUT_SAVE_PHOTO = 373;
	/** "打开预读链接" */
	public static final int SHORTCUT_ENABLE_PREREAD = 415;
	/** "（按5）" */
	public static final int SHORTCUT_PRESS_5_KEY = 416;
	/** "按'0'键快捷进入主页" */
	public static final int PROMPT_PRESS_0_KEY = 417;
	/** "按'9'键快速前进" */
	public static final int PROMPT_PRESS_9_KEY = 418;
	/** "按'7'键快速后退" */
	public static final int PROMPT_PRESS_7_KEY = 419;
	/** "按'*'键立刻刷新" */
	public static final int PROMPT_PRESS_STAR_KEY = 420;
	/** "按'1'键新建窗口" */
	public static final int PROMPR_PRESS_1_NEW_WIN = 421;
	/** "按'3'键切换窗口" */
	public static final int PROMPT_PRESS_3_KEY = 422;
	/** "按'#+2'键打开书签" */
	public static final int PROMPT_PRESS_POUND_2_KEY = 423;
	/** "按'1'键可新建窗口" */
	public static final int PROMPT_PRESS_1_CAN_NEW_WIN = 424;
	/** "按'1'键可加入书签" */
	public static final int PROMPT_PRESS_1_CAN_ADD_BOOKMARK = 425;
	/** "说点什么吧" */
	public static final int SHARE_SAY_SOMETHING = 426;
	/** "写点评论吧" */
	public static final int SHARE_PLEASE_REMARK = 427;
	/** "书签" model_bookmark=true */
	public static final int SHORTCUT_BOOKMARK = 6;
	/** "加入书签" model_bookmark=true */
	public static final int SHORTCUT_ADD_BOOKMARK = 351;
	/** "文件管理" model_bookmark=true */
	public static final int SHORTCUT_FILE_MANAGE = 357;
	/** "系统设置" model_bookmark=false */
	public static final int SHORTCUT_SETTING = 262;
	/** "系统设置" model_bookmark=false */
	public static final int SHORTCUT_SYS_SETTINGS = 262;
	/** "弹出菜单" model_bookmark=false */
	public static final int SHORTCUT_POPUP_MENU = 428;
	/** "请输入刷新间隔(秒)" fun_auto_refresh=true */
	public static final int COMMON_INPUT_INTERVAL = 429;
	/** "刷新时间间隔不能少于30或大于999" fun_auto_refresh=true */
	public static final int COMMON_INTERVAL_LIMIT = 430;
	/** "定时刷新" fun_auto_refresh=true */
	public static final int MENU_AUTO_REFRESH = 431;
	/** "您现在使用的是" model_blackberry_net_adapter=true */
	public static final int NETWORK_NOW_YOU_ARE_USING = 432;
	/** "移动网络" model_blackberry_net_adapter=true */
	public static final int NETWORK_MOBILE_NETWORKS = 433;
	/** "WI-FI" model_blackberry_net_adapter=true */
	public static final int NETWORK_WI_FI = 434;
	/** "WI-FI" model_blackberry_wifi=true */
	public static final int SYS_CONFIG_WI_FI = 434;
	/** "检查更新" fun_update_check=true */
	public static final int UPDATE_CHECK_CHECK_UPDATES = 435;
	/** "查看详情" fun_update_check=true */
	public static final int UPDATE_CHECK_DETAILS = 436;
	/** "服务器繁忙，请稍候更新！" fun_update_check=true */
	public static final int UPDATE_CHECK_SERVER_BUSY = 437;
	/** "升级包下载地址(用自带浏览器直接下载):" fun_update_check=true */
	public static final int UPDATE_CHECK_PACKAGE_URL = 438;
	/** "" fun_update_check=true */
	public static final int UPDATE_CHECK_ = 439;
	/** "下载引导安装地址" fun_update_check=true */
	public static final int UPDATE_CHECK_DOWNLOAD_URL = 440;
	/** "客户端升级" fun_update_check=true */
	public static final int UPDATE_CHECK_UPDATE = 441;
	/** "默认皮肤" model_quality_gui=true */
	public static final int SKIN_DEFAULT = 442;
	/** "夜间模式" model_quality_gui=true */
	public static final int SKIN_NIGHT = 443;
	/** "OMA Download" fun_oma_dw=true */
	public static final int OMA_DOWNLOAD = 444;
	/** "确定通过oma协议下载文件?" fun_oma_dw=true */
	public static final int OMA_CONFIRM = 445;
	/** "Type" fun_oma_dw=true */
	public static final int OMA_TYPE = 446;
	/** "Name" fun_oma_dw=true */
	public static final int OMA_NAME = 447;
	/** "Size" fun_oma_dw=true */
	public static final int OMA_SIZE = 448;
	/** "Vendor" fun_oma_dw=true */
	public static final int OMA_VENDOR = 449;
	/** "ObjectURI" fun_oma_dw=true */
	public static final int OMA_OBJECT_URI = 450;
	/** "InstallNotifyURI" fun_oma_dw=true */
	public static final int OMA_NOTIFY_URI = 451;
	/** "NextURI" fun_oma_dw=true */
	public static final int OMA_NEXT_URI = 452;
	/** "InstallParam" fun_oma_dw=true */
	public static final int OMA_INSTALL_PARAM = 453;
	/** "OMA 描述错误，OjbectURI 不存在" fun_oma_dw=true */
	public static final int OMA_ERROR_INFO = 454;
	/** "文件系统" model_file=true */
	public static final int FILE_SYS = 455;
	/** "返回" model_file=true */
	public static final int FILE_SYS_BACK = 8;
	/** "菜单" model_file=true */
	public static final int FILE_SYS_MENU = 3;
	/** "打开" model_file=true */
	public static final int FILE_SYS_OPEN = 4;
	/** "删除" model_file=true */
	public static final int FILE_SYS_DELETE = 18;
	/** "复制" model_file=true */
	public static final int FILE_SYS_COPY = 2;
	/** "粘贴" model_file=true */
	public static final int FILE_SYS_PASTE = 400;
	/** "重命名" model_file=true */
	public static final int FILE_SYS_RENAME = 456;
	/** "操作" model_file=true */
	public static final int FILE_SYS_OPERATE = 457;
	/** "属性" model_file=true */
	public static final int FILE_SYS_ATTRIBUTE = 458;
	/** "位置" model_file=true */
	public static final int FILE_SYS_LOCATION = 459;
	/** "大小" model_file=true */
	public static final int FILE_SYS_SIZE = 460;
	/** "修改时间" model_file=true */
	public static final int FILE_SYS_MODIFY_TIME = 461;
	/** "可读" model_file=true */
	public static final int FILE_SYS_READABLE = 462;
	/** "可写" model_file=true */
	public static final int FILE_SYS_WRITABLE = 463;
	/** "隐藏" model_file=true */
	public static final int FILE_SYS_HIDDEN = 464;
	/** "名字" model_file=true */
	public static final int FILE_SYS_NAME = 465;
	/** "复制成功,选择文件夹粘贴." model_file=true */
	public static final int FILE_SYS_PASTE_TIP_SELECT_CATALOG = 466;
	/** "请先复制文件!" model_file=true */
	public static final int FILE_SYS_PASTE_TIP_COPY_FIRST = 467;
	/** "确定" model_file=true */
	public static final int FILE_SYS_SURE = 28;
	/** "退出" model_file=true */
	public static final int FILE_SYS_EXIT = 332;
	/** "选择文件" model_file=true */
	public static final int FILE_SYS_SELECT_FILE = 468;
	/** "文件操作失败!" model_file=true */
	public static final int FILE_SYS_TIP_FAILED = 469;
	/** "下载" model_file=true */
	public static final int FILE_SYS_DOWNLOAD = 96;
	/** "文件名" model_file=true */
	public static final int FILE_SYS_FILE_NAME = 110;
	/** "请输入文件名" model_file=true */
	public static final int FILE_SYS_TIP_INPUT_FILENAME = 470;
	/** "保存路径" model_file=true */
	public static final int FILE_SYS_SAVE_CATALOG = 471;
	/** "请选择目录" model_file=true */
	public static final int FILE_SYS_SELECT_CATALOG = 472;
	/** "保存" model_file=true */
	public static final int FILE_SYS_SAVE = 25;
	/** "*请检查文件名是否过长" model_file=true */
	public static final int FILE_SYS_TIP_CHECK_FILENAME_LENGTH = 473;
	/** "*请检查文件名是否包含特殊字符" model_file=true */
	public static final int FILE_SYS_TIP_CHECK_FILENAME_CHAR = 474;
	/** "文件已经存在,如果要保存,请先修改文件名!" model_file=true */
	public static final int FILE_SYS_TIP_FILENAME_EXISTS = 475;
	/** "创建文件失败" model_file=true */
	public static final int FILE_SYS_TIP_CREATE_FAILED = 476;
	/** "建议修改文件管理权限." model_file=true */
	public static final int FILE_SYS_TIP_MODIFY_PERMISSION = 477;
	/** "请尝试其他目录" model_file=true */
	public static final int FILE_SYS_TIP_TRY_OTHER_CATALOG = 478;
	/** "*因手机限制，UC将此文件改名下载；" model_file=true */
	public static final int FILE_SYS_TIP_RENAMED = 479;
	/** "进入存储卡或多媒体资料的下载目录，将文件中的“_”修改为“.”即可正常安装。" model_file=true */
	public static final int FILE_SYS_TIP_MODIFY_FILENAME = 480;
	/** "成功添加下载任务" model_file=true */
	public static final int FILE_SYS_TIP_ADD_DOWNLOAD_TASK = 481;
	/** "文件下载成功" model_file=true */
	public static final int FILE_SYS_TIP_DOWNLOAD_SUCCESS = 482;
	/** "该文件不支持断点续传,暂停后将重新下载,是否继续?" model_file=true */
	public static final int FILE_SYS_TIP_CANNOT_CONTINUE = 483;
	/** "正在下载文件,您确定要退出吗?" model_file=true */
	public static final int FILE_SYS_CONFIRM_EXIT = 484;
	/** "图像" model_file=true */
	public static final int FILE_SYS_CATALOG_IMAGE = 485;
	/** "音乐" model_file=true */
	public static final int FILE_SYS_CATALOG_MUSIC = 486;
	/** "铃声" model_file=true */
	public static final int FILE_SYS_CATALOG_RING = 487;
	/** "照片" model_file=true */
	public static final int FILE_SYS_CATALOG_PHOTO = 488;
	/** "视频" model_file=true */
	public static final int FILE_SYS_CATALOG_VIDEO = 489;
	/** "撤销已选" model_file=true */
	public static final int FILE_SYS_CANCEL_SELECTED = 490;
	/** "保存网页" model_file=true */
	public static final int FILE_SYS_SAVE_PAGE = 491;
	/** "已保存网页" model_file=true */
	public static final int FILE_SYS_SAVED_PAGE = 492;
	/** "*温馨提示*" model_file=true */
	public static final int FILE_SYS_TIPS_TITLE = 493;
	/** "*部分手机限制文件名不能过长" model_file=true */
	public static final int FILE_SYS_TIP_MIND_TOO_LONG = 494;
	/** "*部分手机限制文件名不能为中文" model_file=true */
	public static final int FILE_SYS_TIP_MIND_CHINESE_CHARACTER = 495;
	/** "*部分手机限制文件名中不能含有特殊字符" model_file=true */
	public static final int FILE_SYS_TIP_MIND_SPECIAL_CHARACTER = 496;
	/** "*请确认保存路径非根目录" model_file=true */
	public static final int FILE_SYS_TIP_MIND_ROOT_CATALG = 497;
	/** "保存成功,在\"菜单/打开/已保存网页\"中打开" model_file=true */
	public static final int FILE_SYS_TIP_PAGE_SAVE_SUCCESS = 498;
	/** "抱歉，本版本不兼容旧版的保存页面数据" model_file=true */
	public static final int FILE_SYS_TIP_INCOMPATIBLE = 499;
	/** "窗口切换" model_file=true */
	public static final int DOWNLOAD_SYS_SWITCH_WINDOW = 500;
	/** "退出管理" model_file=true */
	public static final int DOWNLOAD_SYS_EXIT = 501;
	/** "下载管理" model_file=true */
	public static final int DOWNLOAD_SYS_MANAGER = 359;
	/** "暂停下载" model_file=true */
	public static final int DOWNLOAD_SYS_PAUSE = 502;
	/** "继续下载" model_file=true */
	public static final int DOWNLOAD_SYS_CONTINUE = 503;
	/** "重新下载" model_file=true */
	public static final int DOWNLOAD_SYS_RESTART = 504;
	/** "删除任务" model_file=true */
	public static final int DOWNLOAD_SYS_DELETE = 505;
	/** "等待" model_file=true */
	public static final int DOWNLOAD_SYS_WAITTING = 506;
	/** "暂停" model_file=true */
	public static final int DOWNLOAD_SYS_STATE_PAUSED = 148;
	/** "完成" model_file=true */
	public static final int DOWNLOAD_SYS_STATE_FINISHED = 507;
	/** "错误" model_file=true */
	public static final int DOWNLOAD_SYS_STATE_ERROR = 103;
	/** "删除源文件" model_file=true */
	public static final int DOWNLOAD_SYS_DELETE_FILE = 508;
	/** "已经下载任务" model_file=true */
	public static final int DOWNLOAD_SYS_TASK_FINISHED = 509;
	/** "正在下载任务" model_file=true */
	public static final int DOWNLOAD_SYS_TASK_BEING_DOWNLOADED = 510;
	/** "" model_file=true */
	public static final int DOWNLOAD_SYS_TEMP = 439;
	/** "详细信息" model_file=true */
	public static final int DOWNLOAD_SYS_TASK_INFO = 511;
	/** "保存路径" model_file=true */
	public static final int DOWNLOAD_SYS_SAVE_CATALOG = 471;
	/** "文件大小" model_file=true */
	public static final int DOWNLOAD_SYS_FILE_SIZE = 512;
	/** "已经下载" model_file=true */
	public static final int DOWNLOAD_SYS_DOWNLOADED_SIZE = 513;
	/** "速度" model_file=true */
	public static final int DOWNLOAD_SYS_DOWNLOAD_SPPED = 514;
	/** "文件管理" model_file=true */
	public static final int WNLOAD_SYS_MENU_FILE_MANAGE = 357;
	/** "支持断点续传" model_file=true */
	public static final int DOWNLOAD_SYS_CONTINUED_DOWNLOADING = 515;
	/** "删除全部" model_file=true */
	public static final int DOWNLOAD_SYS_DELTE_ALL = 19;
	/** "创建文件失败" model_file=true */
	public static final int DOWNLOAD_SYS_CREATE_FAILED = 476;
	/** "上传" model_file=true */
	public static final int DOWNLOAD_SYS_UPLOAD = 95;
	/** "磁盘空间不足" model_file=true */
	public static final int DOWNLOAD_SYS_NOT_ENOUGH_DISK_SPACE = 516;
	/** "剩余" model_file=true */
	public static final int DOWNLOAD_SYS_REMAINING_SIZE = 517;
	/** "新建下载" model_file=true */
	public static final int DOWNLOAD_SYS_NEW_TASK = 518;
	/** "正在下载" model_file=true */
	public static final int DOWNLOAD_SYS_TYPE_BEING_DOWNLOADED = 519;
	/** "已下载" model_file=true */
	public static final int DOWNLOAD_SYS_TYPE_FINISHED = 520;
	/** "全部开始" model_file=true */
	public static final int DOWNLOAD_SYS_RESTART_ALL = 521;
	/** "全部暂停" model_file=true */
	public static final int DOWNLOAD_SYS_PAUSE_ALL = 522;
	/** "UC浏览器" model_file=true */
	public static final int DOWNLOAD_SYS_BY_UC = 523;
	/** "自带浏览器" model_file=true */
	public static final int DOWNLOAD_SYS_BY_WAP = 255;
	/** "主题文件已下载完成，是否安装?" model_file=true */
	public static final int DOWNLOAD_SYS_INSTALL_CONFIRM = 524;
	/** "安装主题" model_file=true */
	public static final int DOWNLOAD_SYS_INSTALL_THEME = 525;
	/** "主题文件已下载完成，请到下载管理安装" model_file=true */
	public static final int DOWNLOAD_SYS_TIP_DOWNLOADED_THEME = 526;
	/** "已下载完成,是否打开?" model_file=true */
	public static final int DOWNLOAD_SYS_TIP_DOWNLOADED_FILE = 527;
	/** "打开文件" model_file=true */
	public static final int DOWNLOAD_SYS_OPEN = 528;
	/** "下载完成提示" model_file=true */
	public static final int DOWNLOAD_SYS_TIP_DOWNLOADED = 529;
	/** "安装提示" model_file=true */
	public static final int DOWNLOAD_SYS_TIP_SETTING = 530;
	/** "关闭提示" model_file=true */
	public static final int DOWNLOAD_SYS_CLOSE_TIP = 531;
	/** "开启提示" model_file=true */
	public static final int DOWNLOAD_SYS_OPEN_TIP = 532;
	/** "评论" model_file=true */
	public static final int DOWNLOAD_SYS_EVALUATE = 533;
	/** "恢复默认" model_shortcut=TRUE */
	public static final int SHORTCUT_RESTORE_DEFAULT = 361;
	/** "空键值" model_shortcut=TRUE */
	public static final int SHORTCUT_EMPTY_KEY = 52;
	/** "该快捷键不能修改!" model_shortcut=TRUE */
	public static final int SHORTCUT_CANNOT_MODIFY = 534;
	/** "保存成功!" model_shortcut=TRUE */
	public static final int SHORTCUT_SAVE_SUCCESSFUL = 535;

}
